// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.1 (64-bit)
// Version: 2022.1
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module toe_top_generate_ipv4_512_s (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        txEng_tcpPkgBuffer6_dout,
        txEng_tcpPkgBuffer6_num_data_valid,
        txEng_tcpPkgBuffer6_fifo_cap,
        txEng_tcpPkgBuffer6_empty_n,
        txEng_tcpPkgBuffer6_read,
        txEng_ipMetaFifo_dout,
        txEng_ipMetaFifo_num_data_valid,
        txEng_ipMetaFifo_fifo_cap,
        txEng_ipMetaFifo_empty_n,
        txEng_ipMetaFifo_read,
        txEng_ipTupleFifo_dout,
        txEng_ipTupleFifo_num_data_valid,
        txEng_ipTupleFifo_fifo_cap,
        txEng_ipTupleFifo_empty_n,
        txEng_ipTupleFifo_read,
        ipTxData_internal_din,
        ipTxData_internal_num_data_valid,
        ipTxData_internal_fifo_cap,
        ipTxData_internal_full_n,
        ipTxData_internal_write
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;
parameter    ap_const_lv512_lc_3 = 512'd0;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [576:0] txEng_tcpPkgBuffer6_dout;
input  [1:0] txEng_tcpPkgBuffer6_num_data_valid;
input  [1:0] txEng_tcpPkgBuffer6_fifo_cap;
input   txEng_tcpPkgBuffer6_empty_n;
output   txEng_tcpPkgBuffer6_read;
input  [15:0] txEng_ipMetaFifo_dout;
input  [5:0] txEng_ipMetaFifo_num_data_valid;
input  [5:0] txEng_ipMetaFifo_fifo_cap;
input   txEng_ipMetaFifo_empty_n;
output   txEng_ipMetaFifo_read;
input  [63:0] txEng_ipTupleFifo_dout;
input  [5:0] txEng_ipTupleFifo_num_data_valid;
input  [5:0] txEng_ipTupleFifo_fifo_cap;
input   txEng_ipTupleFifo_empty_n;
output   txEng_ipTupleFifo_read;
output  [1023:0] ipTxData_internal_din;
input  [1:0] ipTxData_internal_num_data_valid;
input  [1:0] ipTxData_internal_fifo_cap;
input   ipTxData_internal_full_n;
output   ipTxData_internal_write;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg txEng_tcpPkgBuffer6_read;
reg txEng_ipMetaFifo_read;
reg txEng_ipTupleFifo_read;
reg[1023:0] ipTxData_internal_din;
reg ipTxData_internal_write;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
wire   [1:0] gi_state_load_load_fu_200_p1;
wire   [0:0] grp_nbreadreq_fu_118_p3;
reg    ap_predicate_op26_read_state1;
reg    ap_predicate_op51_read_state1;
wire   [0:0] tmp_i_nbreadreq_fu_132_p3;
wire   [0:0] tmp_544_i_nbreadreq_fu_140_p3;
reg    ap_predicate_op62_read_state1;
reg    ap_predicate_op63_read_state1;
reg    ap_done_reg;
reg    ap_block_state1_pp0_stage0_iter0;
reg   [1:0] gi_state_load_reg_464;
reg   [0:0] tmp_i_348_reg_468;
reg    ap_predicate_op82_write_state2;
reg   [0:0] tmp_543_i_reg_498;
reg    ap_predicate_op91_write_state2;
reg    ap_block_state2_pp0_stage0_iter1;
reg    ap_block_pp0_stage0_subdone;
reg   [1:0] gi_state;
reg   [15:0] header_idx_3;
reg   [159:0] header_header_V_3;
reg    txEng_ipMetaFifo_blk_n;
wire    ap_block_pp0_stage0;
reg    txEng_ipTupleFifo_blk_n;
reg    ipTxData_internal_blk_n;
reg    txEng_tcpPkgBuffer6_blk_n;
reg    ap_block_pp0_stage0_11001;
wire   [511:0] tmp_data_V_4_fu_213_p1;
wire   [511:0] p_Result_208_fu_231_p5;
wire   [0:0] icmp_ln82_2_fu_225_p2;
reg   [64:0] tmp_reg_485;
wire   [511:0] p_Result_207_fu_293_p5;
wire   [0:0] icmp_ln82_fu_287_p2;
reg   [576:0] txEng_tcpPkgBuffer6_read_reg_502;
wire   [511:0] ap_phi_reg_pp0_iter0_currWord_data_V_reg_167;
reg   [511:0] ap_phi_reg_pp0_iter1_currWord_data_V_reg_167;
wire   [511:0] ap_phi_reg_pp0_iter0_sendWord_data_V_16_reg_176;
reg   [511:0] ap_phi_reg_pp0_iter1_sendWord_data_V_16_reg_176;
wire   [1:0] select_ln883_cast_i_fu_265_p3;
wire   [0:0] grp_fu_187_p3;
wire   [15:0] grp_fu_195_p2;
wire   [159:0] p_Result_13_fu_407_p5;
wire   [1023:0] zext_ln174_70_fu_438_p1;
reg    ap_block_pp0_stage0_01001;
wire   [1023:0] zext_ln174_fu_455_p1;
wire   [1023:0] p_07_fu_460_p1;
wire   [24:0] shl_ln76_2_fu_217_p3;
wire   [0:0] xor_ln883_fu_259_p2;
wire   [24:0] shl_ln_fu_279_p3;
wire   [15:0] length_V_1_fu_343_p2;
wire   [7:0] trunc_ln674_fu_359_p1;
wire   [7:0] tmp_545_i9_fu_349_p4;
wire   [15:0] p_Result_s_fu_363_p3;
wire   [159:0] p_Result_204_fu_371_p5;
wire   [31:0] tmp_dstIp_V_fu_327_p4;
wire   [159:0] p_Result_205_fu_383_p5;
wire   [31:0] tmp_srcIp_V_fu_323_p1;
wire   [159:0] p_Result_206_fu_395_p5;
wire   [576:0] tmp_s_fu_431_p3;
wire   [512:0] or_ln_fu_443_p3;
wire  signed [543:0] sext_ln174_fu_451_p1;
reg   [0:0] ap_NS_fsm;
reg    ap_idle_pp0_0to0;
reg    ap_reset_idle_pp0;
wire    ap_enable_pp0;
reg    ap_condition_176;
reg    ap_condition_198;
reg    ap_condition_167;
reg    ap_condition_210;
reg    ap_condition_68;
reg    ap_condition_235;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_done_reg = 1'b0;
#0 gi_state = 2'd0;
#0 header_idx_3 = 16'd0;
#0 header_header_V_3 = 160'd1180591620717411303493;
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_enable_reg_pp0_iter1 <= ap_start;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_167)) begin
        if ((1'b1 == ap_condition_198)) begin
            ap_phi_reg_pp0_iter1_currWord_data_V_reg_167 <= tmp_data_V_4_fu_213_p1;
        end else if ((1'b1 == ap_condition_176)) begin
            ap_phi_reg_pp0_iter1_currWord_data_V_reg_167 <= p_Result_208_fu_231_p5;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_currWord_data_V_reg_167 <= ap_phi_reg_pp0_iter0_currWord_data_V_reg_167;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_167)) begin
        if (((gi_state_load_load_fu_200_p1 == 2'd1) & (icmp_ln82_fu_287_p2 == 1'd1))) begin
            ap_phi_reg_pp0_iter1_sendWord_data_V_16_reg_176 <= p_Result_207_fu_293_p5;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_sendWord_data_V_16_reg_176 <= ap_phi_reg_pp0_iter0_sendWord_data_V_16_reg_176;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_167)) begin
        if ((1'b1 == ap_condition_68)) begin
            gi_state <= 2'd2;
        end else if ((1'b1 == ap_condition_210)) begin
            gi_state <= 2'd0;
        end else if ((gi_state_load_load_fu_200_p1 == 2'd1)) begin
            gi_state <= 2'd2;
        end else if (((grp_nbreadreq_fu_118_p3 == 1'd1) & (gi_state == 2'd2))) begin
            gi_state <= select_ln883_cast_i_fu_265_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_544_i_nbreadreq_fu_140_p3 == 1'd1) & (tmp_i_nbreadreq_fu_132_p3 == 1'd1) & (gi_state == 2'd0) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        header_idx_3 <= 16'd0;
    end else if ((((grp_nbreadreq_fu_118_p3 == 1'd1) & (gi_state == 2'd2) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln82_2_fu_225_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001)) | ((gi_state_load_load_fu_200_p1 == 2'd1) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln82_fu_287_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        header_idx_3 <= grp_fu_195_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        gi_state_load_reg_464 <= gi_state;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_544_i_nbreadreq_fu_140_p3 == 1'd1) & (tmp_i_nbreadreq_fu_132_p3 == 1'd1) & (gi_state == 2'd0) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        header_header_V_3 <= p_Result_13_fu_407_p5;
    end
end

always @ (posedge ap_clk) begin
    if (((gi_state == 2'd3) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        tmp_543_i_reg_498 <= grp_nbreadreq_fu_118_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((gi_state == 2'd2) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        tmp_i_348_reg_468 <= grp_nbreadreq_fu_118_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_nbreadreq_fu_118_p3 == 1'd1) & (gi_state == 2'd2) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        tmp_reg_485 <= {{txEng_tcpPkgBuffer6_dout[576:512]}};
    end
end

always @ (posedge ap_clk) begin
    if (((ap_predicate_op51_read_state1 == 1'b1) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        txEng_tcpPkgBuffer6_read_reg_502 <= txEng_tcpPkgBuffer6_dout;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b0)) begin
        ap_idle_pp0_0to0 = 1'b1;
    end else begin
        ap_idle_pp0_0to0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (ap_idle_pp0_0to0 == 1'b1))) begin
        ap_reset_idle_pp0 = 1'b1;
    end else begin
        ap_reset_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0) & (ap_predicate_op91_write_state2 == 1'b1)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0) & (ap_predicate_op82_write_state2 == 1'b1)) | ((gi_state_load_reg_464 == 2'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0)))) begin
        ipTxData_internal_blk_n = ipTxData_internal_full_n;
    end else begin
        ipTxData_internal_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_235)) begin
        if ((ap_predicate_op91_write_state2 == 1'b1)) begin
            ipTxData_internal_din = p_07_fu_460_p1;
        end else if ((gi_state_load_reg_464 == 2'd1)) begin
            ipTxData_internal_din = zext_ln174_fu_455_p1;
        end else if ((ap_predicate_op82_write_state2 == 1'b1)) begin
            ipTxData_internal_din = zext_ln174_70_fu_438_p1;
        end else begin
            ipTxData_internal_din = 'bx;
        end
    end else begin
        ipTxData_internal_din = 'bx;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_op91_write_state2 == 1'b1)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_op82_write_state2 == 1'b1)) | ((gi_state_load_reg_464 == 2'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        ipTxData_internal_write = 1'b1;
    end else begin
        ipTxData_internal_write = 1'b0;
    end
end

always @ (*) begin
    if (((ap_done_reg == 1'b0) & (ap_predicate_op62_read_state1 == 1'b1) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        txEng_ipMetaFifo_blk_n = txEng_ipMetaFifo_empty_n;
    end else begin
        txEng_ipMetaFifo_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((ap_predicate_op62_read_state1 == 1'b1) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        txEng_ipMetaFifo_read = 1'b1;
    end else begin
        txEng_ipMetaFifo_read = 1'b0;
    end
end

always @ (*) begin
    if (((ap_done_reg == 1'b0) & (ap_predicate_op63_read_state1 == 1'b1) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        txEng_ipTupleFifo_blk_n = txEng_ipTupleFifo_empty_n;
    end else begin
        txEng_ipTupleFifo_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((ap_predicate_op63_read_state1 == 1'b1) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        txEng_ipTupleFifo_read = 1'b1;
    end else begin
        txEng_ipTupleFifo_read = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_done_reg == 1'b0) & (ap_predicate_op51_read_state1 == 1'b1) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0)) | ((ap_done_reg == 1'b0) & (ap_predicate_op26_read_state1 == 1'b1) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0)))) begin
        txEng_tcpPkgBuffer6_blk_n = txEng_tcpPkgBuffer6_empty_n;
    end else begin
        txEng_tcpPkgBuffer6_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((((ap_predicate_op51_read_state1 == 1'b1) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_predicate_op26_read_state1 == 1'b1) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        txEng_tcpPkgBuffer6_read = 1'b1;
    end else begin
        txEng_tcpPkgBuffer6_read = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = ((ap_done_reg == 1'b1) | ((ap_start == 1'b1) & ((ap_done_reg == 1'b1) | ((ap_predicate_op63_read_state1 == 1'b1) & (txEng_ipTupleFifo_empty_n == 1'b0)) | ((ap_predicate_op62_read_state1 == 1'b1) & (txEng_ipMetaFifo_empty_n == 1'b0)) | ((ap_predicate_op51_read_state1 == 1'b1) & (txEng_tcpPkgBuffer6_empty_n == 1'b0)) | ((ap_predicate_op26_read_state1 == 1'b1) & (txEng_tcpPkgBuffer6_empty_n == 1'b0)))) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (((ipTxData_internal_full_n == 1'b0) & (ap_predicate_op91_write_state2 == 1'b1)) | ((ipTxData_internal_full_n == 1'b0) & (ap_predicate_op82_write_state2 == 1'b1)) | ((gi_state_load_reg_464 == 2'd1) & (ipTxData_internal_full_n == 1'b0)))));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((ap_done_reg == 1'b1) | ((ap_start == 1'b1) & ((ap_done_reg == 1'b1) | ((ap_predicate_op63_read_state1 == 1'b1) & (txEng_ipTupleFifo_empty_n == 1'b0)) | ((ap_predicate_op62_read_state1 == 1'b1) & (txEng_ipMetaFifo_empty_n == 1'b0)) | ((ap_predicate_op51_read_state1 == 1'b1) & (txEng_tcpPkgBuffer6_empty_n == 1'b0)) | ((ap_predicate_op26_read_state1 == 1'b1) & (txEng_tcpPkgBuffer6_empty_n == 1'b0)))) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (((ipTxData_internal_full_n == 1'b0) & (ap_predicate_op91_write_state2 == 1'b1)) | ((ipTxData_internal_full_n == 1'b0) & (ap_predicate_op82_write_state2 == 1'b1)) | ((gi_state_load_reg_464 == 2'd1) & (ipTxData_internal_full_n == 1'b0)))));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((ap_done_reg == 1'b1) | ((ap_start == 1'b1) & ((ap_done_reg == 1'b1) | ((ap_predicate_op63_read_state1 == 1'b1) & (txEng_ipTupleFifo_empty_n == 1'b0)) | ((ap_predicate_op62_read_state1 == 1'b1) & (txEng_ipMetaFifo_empty_n == 1'b0)) | ((ap_predicate_op51_read_state1 == 1'b1) & (txEng_tcpPkgBuffer6_empty_n == 1'b0)) | ((ap_predicate_op26_read_state1 == 1'b1) & (txEng_tcpPkgBuffer6_empty_n == 1'b0)))) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (((ipTxData_internal_full_n == 1'b0) & (ap_predicate_op91_write_state2 == 1'b1)) | ((ipTxData_internal_full_n == 1'b0) & (ap_predicate_op82_write_state2 == 1'b1)) | ((gi_state_load_reg_464 == 2'd1) & (ipTxData_internal_full_n == 1'b0)))));
end

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = ((ap_done_reg == 1'b1) | ((ap_predicate_op63_read_state1 == 1'b1) & (txEng_ipTupleFifo_empty_n == 1'b0)) | ((ap_predicate_op62_read_state1 == 1'b1) & (txEng_ipMetaFifo_empty_n == 1'b0)) | ((ap_predicate_op51_read_state1 == 1'b1) & (txEng_tcpPkgBuffer6_empty_n == 1'b0)) | ((ap_predicate_op26_read_state1 == 1'b1) & (txEng_tcpPkgBuffer6_empty_n == 1'b0)));
end

always @ (*) begin
    ap_block_state2_pp0_stage0_iter1 = (((ipTxData_internal_full_n == 1'b0) & (ap_predicate_op91_write_state2 == 1'b1)) | ((ipTxData_internal_full_n == 1'b0) & (ap_predicate_op82_write_state2 == 1'b1)) | ((gi_state_load_reg_464 == 2'd1) & (ipTxData_internal_full_n == 1'b0)));
end

always @ (*) begin
    ap_condition_167 = ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001));
end

always @ (*) begin
    ap_condition_176 = ((grp_nbreadreq_fu_118_p3 == 1'd1) & (gi_state == 2'd2) & (icmp_ln82_2_fu_225_p2 == 1'd1));
end

always @ (*) begin
    ap_condition_198 = ((grp_nbreadreq_fu_118_p3 == 1'd1) & (gi_state == 2'd2) & (icmp_ln82_2_fu_225_p2 == 1'd0));
end

always @ (*) begin
    ap_condition_210 = ((grp_nbreadreq_fu_118_p3 == 1'd1) & (gi_state == 2'd3) & (grp_fu_187_p3 == 1'd1));
end

always @ (*) begin
    ap_condition_235 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_01001));
end

always @ (*) begin
    ap_condition_68 = ((tmp_544_i_nbreadreq_fu_140_p3 == 1'd1) & (tmp_i_nbreadreq_fu_132_p3 == 1'd1) & (gi_state == 2'd0));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start;

assign ap_phi_reg_pp0_iter0_currWord_data_V_reg_167 = 'bx;

assign ap_phi_reg_pp0_iter0_sendWord_data_V_16_reg_176 = 'bx;

always @ (*) begin
    ap_predicate_op26_read_state1 = ((grp_nbreadreq_fu_118_p3 == 1'd1) & (gi_state == 2'd2));
end

always @ (*) begin
    ap_predicate_op51_read_state1 = ((grp_nbreadreq_fu_118_p3 == 1'd1) & (gi_state == 2'd3));
end

always @ (*) begin
    ap_predicate_op62_read_state1 = ((tmp_544_i_nbreadreq_fu_140_p3 == 1'd1) & (tmp_i_nbreadreq_fu_132_p3 == 1'd1) & (gi_state == 2'd0));
end

always @ (*) begin
    ap_predicate_op63_read_state1 = ((tmp_544_i_nbreadreq_fu_140_p3 == 1'd1) & (tmp_i_nbreadreq_fu_132_p3 == 1'd1) & (gi_state == 2'd0));
end

always @ (*) begin
    ap_predicate_op82_write_state2 = ((tmp_i_348_reg_468 == 1'd1) & (gi_state_load_reg_464 == 2'd2));
end

always @ (*) begin
    ap_predicate_op91_write_state2 = ((gi_state_load_reg_464 == 2'd3) & (tmp_543_i_reg_498 == 1'd1));
end

assign gi_state_load_load_fu_200_p1 = gi_state;

assign grp_fu_187_p3 = txEng_tcpPkgBuffer6_dout[32'd576];

assign grp_fu_195_p2 = (header_idx_3 + 16'd1);

assign grp_nbreadreq_fu_118_p3 = txEng_tcpPkgBuffer6_empty_n;

assign icmp_ln82_2_fu_225_p2 = ((shl_ln76_2_fu_217_p3 < 25'd160) ? 1'b1 : 1'b0);

assign icmp_ln82_fu_287_p2 = ((shl_ln_fu_279_p3 < 25'd160) ? 1'b1 : 1'b0);

assign length_V_1_fu_343_p2 = (txEng_ipMetaFifo_dout + 16'd40);

assign or_ln_fu_443_p3 = {{1'd1}, {ap_phi_reg_pp0_iter1_sendWord_data_V_16_reg_176}};

assign p_07_fu_460_p1 = txEng_tcpPkgBuffer6_read_reg_502;

assign p_Result_13_fu_407_p5 = {{p_Result_206_fu_395_p5[159:80]}, {8'd6}, {p_Result_206_fu_395_p5[71:0]}};

assign p_Result_204_fu_371_p5 = {{header_header_V_3[159:32]}, {p_Result_s_fu_363_p3}, {header_header_V_3[15:0]}};

assign p_Result_205_fu_383_p5 = {{tmp_dstIp_V_fu_327_p4}, {p_Result_204_fu_371_p5[127:0]}};

assign p_Result_206_fu_395_p5 = {{p_Result_205_fu_383_p5[159:128]}, {tmp_srcIp_V_fu_323_p1}, {p_Result_205_fu_383_p5[95:0]}};

assign p_Result_207_fu_293_p5 = {{ap_const_lv512_lc_3[511:160]}, {header_header_V_3}};

assign p_Result_208_fu_231_p5 = {{tmp_data_V_4_fu_213_p1[511:160]}, {header_header_V_3}};

assign p_Result_s_fu_363_p3 = {{trunc_ln674_fu_359_p1}, {tmp_545_i9_fu_349_p4}};

assign select_ln883_cast_i_fu_265_p3 = ((xor_ln883_fu_259_p2[0:0] == 1'b1) ? 2'd3 : 2'd0);

assign sext_ln174_fu_451_p1 = $signed(or_ln_fu_443_p3);

assign shl_ln76_2_fu_217_p3 = {{header_idx_3}, {9'd0}};

assign shl_ln_fu_279_p3 = {{header_idx_3}, {9'd0}};

assign tmp_544_i_nbreadreq_fu_140_p3 = txEng_ipTupleFifo_empty_n;

assign tmp_545_i9_fu_349_p4 = {{length_V_1_fu_343_p2[15:8]}};

assign tmp_data_V_4_fu_213_p1 = txEng_tcpPkgBuffer6_dout[511:0];

assign tmp_dstIp_V_fu_327_p4 = {{txEng_ipTupleFifo_dout[63:32]}};

assign tmp_i_nbreadreq_fu_132_p3 = txEng_ipMetaFifo_empty_n;

assign tmp_s_fu_431_p3 = {{tmp_reg_485}, {ap_phi_reg_pp0_iter1_currWord_data_V_reg_167}};

assign tmp_srcIp_V_fu_323_p1 = txEng_ipTupleFifo_dout[31:0];

assign trunc_ln674_fu_359_p1 = length_V_1_fu_343_p2[7:0];

assign xor_ln883_fu_259_p2 = (grp_fu_187_p3 ^ 1'd1);

assign zext_ln174_70_fu_438_p1 = tmp_s_fu_431_p3;

assign zext_ln174_fu_455_p1 = $unsigned(sext_ln174_fu_451_p1);

endmodule //toe_top_generate_ipv4_512_s
